### ISSUE TITLE
hellow is mined premine

### ISSUE THREAD

**Issue by andimion666** [hughesjs/incendium#1]
good I have your premine, if you want I give it back to you, I did not realize when putting it to mine, thanks

**Comment by hughesjs** [comment]
How on earth did you manage that? I've been trying to work out what happened...

**Comment by hughesjs** [comment]
@andimion666  I'll start up the nodes again then give you a wallet address to transfer it back to

**Comment by hughesjs** [comment]
@andimion666  I've restarted the blockchain. If you could delete your copy and restart I'd appreciate it. That should solve the issue.
